sudo: required
services:
  - docker

before_install:
  - docker build -t arunjose/multi-docker-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arunjose/multi-docker-client-test npm test -- --coverage

after_success:
  - docker build -t arunjose/multi-docker-frontend ./client
  - docker build -t arunjose/multi-docker-backend ./server
  - docker build -t arunjose/multi-docker-worker ./worker
  - docker build -t arunjose/multi-docker-gateway ./gateway

  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push arunjose/multi-docker-frontend
  - docker push arunjose/multi-docker-gateway
  - docker push arunjose/multi-docker-worker
  - docker push arunjose/multi-docker-backend

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "multi-docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-514088687196"
  bukcet_path: "multi-docker-bucket"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"




