version: '3'
services:
  db:
    image: 'postgres:latest'
  cache:
    image: 'redis:latest'
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
  gateway:
    restart: always
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'

      